station:
  # Token配置
  token:
    # 请求header中的Token属性名
    header: Authorization
    # TokenKey命名头
    domain: 'station:token:'
    # Token密钥，请手动修改
    secret: abcdefghijklmnopqrstuvwxyz
    # Token有效期（单位：分钟）
    expireTime: 60
    # 记住登录有效时间（单位：小时）
    remember: 168
  # 文件配置
  file:
    path:
      # 文件系统根路径，推荐相对路径
      main: E:/test/
  # RSA配置
  rsa:
    # 密钥对有效时长（单位：分钟）
    expire: 10
  #Email配置
  email:
    # 是否开启debug模式
    debug: true
    # 邮件服务器主机地址
    host:
    # 邮件服务器端口
    port:
    # 邮件服务器协议
    protocol:
    # 发件邮箱地址
    email:
    # 发件邮箱授权密码
    password:
  # 线程配置
  thread:
    # 核心线程数
    coreSize: 4
    # 最大线程数
    maxSize: 20
    # 线程存活时间（单位：秒）
    alive: 60
    # 允许线程超时
    allowTimeout: true
  # 任务配置
  task:
    # 允许的任务列表。格式为yml的列表格式
    allowed:
    # 屏蔽的任务列表
    blocked:
  # 接口限制配置
  limit:
    # 是否开启限制策略
    enable: true
  # API日志配置
  api-log:
    # 是否开启API日志功能
    enable: true
    # 当API日志功能开启后，允许的日志等级（与LogLevel枚举类对应），使用英文,隔开。为空则允许全部
    level: debug, info, warning, error
    # 当API日志功能开启后，允许的日志类型（与LogType枚举类对应），使用英文,隔开。为空则允许全部
    type: default, insert, update
  # 权限功能配置
  permission:
    # 权限功能是否开启
    enable: true
  # URL远程指令配置
  command:
    # 是否启用远程指令
    enable: true
    # 远程指令允许名单，当存在值时会使屏蔽名单无效化。格式为yml的列表格式
    allowed:
    # 远程指令屏蔽名单。格式为yml的列表格式
    blocked:
  # API配置
  api:
    # 是否启用API策略
    enable: true
    # 屏蔽的API
    blocked:
      # api路径，多路径用英文,隔开
      # 下面的参数表示了屏蔽"/haha"与"/xixi"两个接口的所有方法，并使用完全匹配，则"/haha/1"不会被屏蔽
      - api: /haha, /xixi
      - api: /test/.*
        # 屏蔽的请求方法，多方法用英文,隔开。包括POST、GET、DELETE等，不区分大小写。没有此参数则表示所有方法。
        method: get
        # 匹配模式，目前支持完全匹配(default)、正则匹配(regex)、前缀匹配(prefix)、后缀匹配(suffix)、包含匹配(contain)。没有此参数则为默认的完全匹配
        mode: regex