spring:
  profiles:
    active: druid, token, redis, file
  application:
    name: Station
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

###############################---mybatis---#########################
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    idea:
      verlif:
        juststation:
          core: debug

server:
  port: 8888