station:
  # Token配置
  token:
    # 请求header中的Token属性名
    header: Authorization
    # TokenKey命名头
    domain: 'station:token:'
    # Token密钥，请手动修改
    secret: abcdefghijklmnopqrstuvwxyz
    # Token有效期（单位：分钟）
    expireTime: 60
    # 记住登录有效时间（单位：小时）
    remember: 168
  # 文件配置
  file:
    path:
      # 文件系统根路径，推荐相对路径
      main: E:/test/
  # RSA配置
  rsa:
    # 密钥对有效时长（单位：分钟）
    expire: 10
  #Email配置
  email:
    # 是否开启debug模式
    debug: true
    # 邮件服务器主机地址
    host:
    # 邮件服务器端口
    port:
    # 邮件服务器协议
    protocol:
    # 发件邮箱地址
    email:
    # 发件邮箱授权密码
    password:
  # 线程配置
  thread:
    # 核心线程数
    coreSize: 4
    # 最大线程数
    maxSize: 20
    # 线程存活时间（单位：秒）
    alive: 60
    # 允许线程超时
    allowTimeout: true
  # 定时任务配置
  schedule:
    # 允许的定时任务列表。格式为yml的列表格式
    allowed:
    # 屏蔽的定时任务列表
    blocked:
  # URL远程指令配置
  command:
    # 远程指令允许名单，当存在值时会使屏蔽名单无效化。格式为yml的列表格式
    allowed:
    # 远程指令屏蔽名单。格式为yml的列表格式
    blocked: